name: Godot Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  export:
    name: Export Game
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.5.1
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
        env:
          GODOT_VERSION: 4.5.1
      
      - name: Build Linux
        run: |
          mkdir -v -p build/linux
          godot --headless --verbose --export-release "Linux" build/linux/game.x86_64
      
      - name: Build Windows
        run: |
          mkdir -v -p build/windows
          godot --headless --verbose --export-release "Windows Desktop" build/windows/game.exe
      
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux
      
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows
